name: build
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
  # Build the image every Sunday
    - cron: '0 0 * * 0'

jobs:
  build-sign-publish:
    uses: chimbosonic/container-build-tools/.github/workflows/build-publish-container-resuable-workflow.yml@main
    with:
      image-name: qbittorrent
      image-repo-name: chimbosonic
      image-author: Alexis Lowe <alexis.lowe@chimbosonic.com>
      image-description: qBittorrent BitTorrent client 
      image-documentation: https://github.com/chimbosonic/qbittorrent-container/blob/main/README.md
    secrets: inherit